// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1yfQwuhzYCAvhpTELUNoq-YhyEu1q5o4',
    appId: '1:466492016943:web:985c52df363e8559b9b9da',
    messagingSenderId: '466492016943',
    projectId: 'chat-app-b9b34',
    authDomain: 'chat-app-b9b34.firebaseapp.com',
    storageBucket: 'chat-app-b9b34.appspot.com',
    measurementId: 'G-3YF2TXGKF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStMGpRkKXqNe61A5jAe8JZQeJC0fZ8Mk',
    appId: '1:466492016943:android:0bf6bbeca88dc281b9b9da',
    messagingSenderId: '466492016943',
    projectId: 'chat-app-b9b34',
    storageBucket: 'chat-app-b9b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADz3xLbsCaXlZAY7QRxmuDzW9EfA37Ivw',
    appId: '1:466492016943:ios:c6ce6ce374571166b9b9da',
    messagingSenderId: '466492016943',
    projectId: 'chat-app-b9b34',
    storageBucket: 'chat-app-b9b34.appspot.com',
    iosBundleId: 'com.shravan.jkbFirebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADz3xLbsCaXlZAY7QRxmuDzW9EfA37Ivw',
    appId: '1:466492016943:ios:c6ce6ce374571166b9b9da',
    messagingSenderId: '466492016943',
    projectId: 'chat-app-b9b34',
    storageBucket: 'chat-app-b9b34.appspot.com',
    iosBundleId: 'com.shravan.jkbFirebaseChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1yfQwuhzYCAvhpTELUNoq-YhyEu1q5o4',
    appId: '1:466492016943:web:e81e8e2c56d26256b9b9da',
    messagingSenderId: '466492016943',
    projectId: 'chat-app-b9b34',
    authDomain: 'chat-app-b9b34.firebaseapp.com',
    storageBucket: 'chat-app-b9b34.appspot.com',
    measurementId: 'G-F4V4X6M1P5',
  );
}
